openapi: 3.0.0

info:
  title: Test Foundarium
  description: |-
    API для управления списком поездок.
    
    Требования к API:
      - Дан список автомобилей.
      - Дан список пользователей.
      - В один момент времени один пользователь может управлять только одним автомобилем.
      - В один момент времени одним автомобилем может управлять только один пользователь.
        
  version: 0.0.2

servers:
  - url: http://test.foundarium/api/driving
    description: Localhost

paths:

  /create:
    post:
      summary: Создание поездки.
      tags:
        - API
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                car_id:
                  type: integer
                driver_id:
                  type: integer
              required:
                - car_id
                - driver_id
                
      responses:
        '200':
          description: Не удалось создать поездку.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Автомобиль уже используется.
        '201':
          description: Поездка успешно создана.
          content:
            application/json:
              schema:
                type: object
                properties:
                  driving_number:
                    type: integer
                    example: 21
        '400':
          description: Данные невалидны.
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: string
                    example: {"driver_id": ["validation.exists"]}

  /complete:
    put:
      summary: Завершение поездки.
      tags:
        - API
      parameters:
        - name: driving_id
          in: query
          required: true
          description: Идентификатор созданной поездки.
          schema:
            type: integer
            minimum: 1
            
      responses: 
        '200':
          description: Изменение поездки запрещено.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Поездка больше недоступна для изменения.
        '202':
          description: Поездка успешно завершена.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Поездка завершена.
        '400':
          description: Данные невалидны.
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: string
                    example: {"driving_id": ["validation.exists"]}